FROM ubuntu:18.04
MAINTAINER Indrajeet Singh <indraindrajit71@gmail.com>

RUN apt-get update -y
RUN apt-get -y install vim
RUN apt-get -y install apache2
RUN apt-get -y install pwgen
RUN apt-get -y install curl
